#!/usr/bin/env perl
sub on_sel_grab {
    my $query = $_[0]->selection;
    open (my $pipe,'| /home/lovek323/.nix-profile/bin/xclip -in -selection clipboard') or die;
    print $pipe $query;
    close $pipe;
}
sub paste {
    my ($self) = @_;
    my $content = `/home/lovek323/.nix-profile/bin/xclip -loop 1 -out -selection clipboard` ;
    $self->tt_write ($content);
}
sub on_user_command {
    my ($self, $cmd) = @_;
    if ($cmd eq "clipboard:paste") {
        $self->paste;
    }
}
# vim: set ft=perl:
